<?php

namespace Pterodactyl\Tests\Integration\Uptime;

use Pterodactyl\Tests\TestCase;
use Pterodactyl\Uptime\Protocol\Protocol;
use Pterodactyl\Uptime\Protocol\UptimeFormula;
use Pterodactyl\Uptime\Protocol\ProtocolException;

/**
 * The PHP collector must agree byte-for-byte with the Go agent and verifier: these
 * vectors are generated by `go test ./protocol -update` in the UpTime-Server repository.
 */
class UptimeProtocolTest extends TestCase
{
    private function vectors(): array
    {
        return json_decode((string) file_get_contents(__DIR__ . '/fixtures/protocol-v1.json'), true, 512, JSON_THROW_ON_ERROR);
    }

    public function testGoVectorsVerifyInPhp(): void
    {
        $v = $this->vectors()['single'];
        $public = base64_decode($v['public_key']);
        $this->assertSame($v['fingerprint'], Protocol::fingerprint($public), 'fingerprint is stable across languages');
        $this->assertTrue(Protocol::verifySignature($public, $v['payload'], base64_decode($v['signature'])));
        $this->assertSame($v['payload_hash'], Protocol::payloadHash($v['payload']));
        $this->assertSame($v['event_hash'], Protocol::eventHash(Protocol::GENESIS, $v['payload_hash']));
        $fields = Protocol::parsePayload($v['payload']);
        $this->assertSame($v['payload'], Protocol::encode($fields), 'canonical encoding round-trips');

        foreach (['"ts":1790000000000' => '"ts":1790000000001', '"seq":42' => '"seq":43', '"status":"ok"' => '"status":"degraded"'] as $from => $to) {
            $this->assertFalse(Protocol::verifySignature($public, str_replace($from, $to, $v['payload']), base64_decode($v['signature'])), "changed {$from} still verifies");
        }
        $this->assertFalse(Protocol::verifySignature(random_bytes(32), $v['payload'], base64_decode($v['signature'])), 'wrong key accepted');
    }

    public function testGoProofChainAndUptimeAreReproducedInPhp(): void
    {
        $proof = $this->vectors()['proof'];
        $keys = collect($proof['keys'])->keyBy('fingerprint');
        $prev = Protocol::GENESIS;
        $points = [];
        foreach ($proof['events'] as $e) {
            $p = Protocol::parsePayload($e['payload']);
            $this->assertTrue(Protocol::verifySignature(base64_decode($keys[$p['key']]['public_key']), $e['payload'], base64_decode($e['signature'])));
            $this->assertSame($prev, $e['prev_hash']);
            $this->assertSame($e['payload_hash'], Protocol::payloadHash($e['payload']));
            $this->assertSame($e['event_hash'], Protocol::eventHash($e['prev_hash'], $e['payload_hash']));
            $prev = $e['event_hash'];
            $points[] = ['received' => $e['received_at'], 'type' => $p['type'], 'mono' => $p['mono_ms']];
        }

        $params = ['timeout_ms' => $proof['node']['params']['timeout_ms'], 'tolerance_ms' => $proof['node']['params']['tolerance_ms']];
        $outages = [];
        for ($i = 1; $i < count($points); ++$i) {
            array_push($outages, ...UptimeFormula::gapOutages($points[$i - 1], $points[$i], $params));
        }
        if ($open = UptimeFormula::openOutage(end($points)['received'], $params, $proof['range']['to'])) {
            $outages[] = $open;
        }
        $w = UptimeFormula::calculate($outages, $proof['node']['monitoring_started_at'], $proof['range']['from'], $proof['range']['to']);
        $this->assertSame($proof['summary']['covered_ms'], $w['covered_ms']);
        $this->assertSame($proof['summary']['downtime_ms'], $w['downtime_ms']);
        $this->assertSame($proof['summary']['outages'], $outages, 'same outages as the Go reference');
    }

    public function testCanonicalFormIsStrict(): void
    {
        foreach ([
            '{"b":1,"a":2}', '{"a":1, "b":2}', '{"a":01}', '{"a":-1}', '{"a":1.5}', '{"a":"x\"y"}', '{"a":"é"}',
            '{"a":{"b":1}}', '{"a":1,"a":1}', '{"a":1}x', '{"A":1}', '{"a":9007199254740992}', '{}', "{\"a\":\"tab\there\"}", '{"a":"é"}',
        ] as $input) {
            try {
                Protocol::decode($input);
                $this->fail("accepted non-canonical input {$input}");
            } catch (ProtocolException) {
                $this->addToAssertionCount(1);
            }
        }
        $this->assertSame(['a' => 9007199254740991, 'b' => 'ok ~'], Protocol::decode('{"a":9007199254740991,"b":"ok ~"}'));
    }

    public function testUnknownOrMissingFieldsAreRejected(): void
    {
        $fields = Protocol::parsePayload($this->vectors()['single']['payload']);
        $this->expectException(ProtocolException::class);
        Protocol::parsePayload(Protocol::encode($fields + ['hostname' => 'secret-host']));
    }

    public function testDisplayNeverOverstatesUptimeOrCoverage(): void
    {
        $this->assertSame('99.999%', \Pterodactyl\Uptime\Http\Format::percent(99.99999));
        $this->assertSame('No data', \Pterodactyl\Uptime\Http\Format::percent(null));
        $w = ['uptime_percent' => 100.0, 'coverage_percent' => 0.004];
        $this->assertSame(['100%', 'monitored <0.1% of window'], \Pterodactyl\Uptime\Http\Format::window($w));
        $this->assertSame(['100%', 'monitored 12.3% of window'], \Pterodactyl\Uptime\Http\Format::window(['uptime_percent' => 100.0, 'coverage_percent' => 12.39]));
        $this->assertSame(['100%', null], \Pterodactyl\Uptime\Http\Format::window(['uptime_percent' => 100.0, 'coverage_percent' => 100.0]));
    }

    public function testUptimeFormulaEdgeCases(): void
    {
        $t0 = 1_790_000_000_000;
        // Nothing before monitoring began is counted.
        $w = UptimeFormula::calculate([], $t0, $t0 - 86_400_000, $t0 + 3_600_000);
        $this->assertSame(3_600_000, $w['covered_ms']);
        $this->assertEqualsWithDelta(100.0, $w['uptime_percent'], 1e-9);
        $this->assertLessThan(5, $w['coverage_percent']);
        // No monitoring: no data, never 100%.
        $this->assertNull(UptimeFormula::calculate([], null, $t0, $t0 + 1000)['uptime_percent']);
        // A quick reboot is still downtime (boot instant from the signed uptime).
        $out = UptimeFormula::gapOutages(['received' => $t0, 'type' => 'heartbeat', 'mono' => 1], ['received' => $t0 + 20_000, 'type' => 'boot', 'mono' => 15_000], ['timeout_ms' => 90_000, 'tolerance_ms' => 30_000]);
        $this->assertSame([['start' => $t0, 'end' => $t0 + 5_000, 'cause' => 'reboot']], $out);
    }
}
